### ISSUE TITLE
Wrong Armor Hud Position

### ISSUE THREAD

**Issue by Soufre** [matthewperiut/NoHunger#2]
The armor hud's position seems unaffected, even when only using the [latest version](https://modrinth.com/mod/nohunger/version/alVeuihY) of No Hunger, [Mod Menu](https://modrinth.com/mod/modmenu/version/11.0.1), the [Fabric API](https://modrinth.com/mod/fabric-api/version/0.100.4+1.21) and [Cloth Config](https://modrinth.com/mod/cloth-config/version/15.0.127+fabric). **No resource packs loaded either.**

**_Examples below._**
![2024-07-01_11 28 10](https://github.com/matthewperiut/NoHunger/assets/96512010/0e8694f9-e786-4148-8a8a-7d034d357cff)
![2024-07-01_11 28 33](https://github.com/matthewperiut/NoHunger/assets/96512010/c99e9c03-8199-4a02-a082-07b1319bba38)
![2024-07-01_11 35 32](https://github.com/matthewperiut/NoHunger/assets/96512010/12cdf7d6-feb6-4353-a1ac-b8e525042707)

**Comment by matthewperiut** [comment]
Could you send the log? I made the Mixin not required so it should say why it isn't applied

**Comment by Soufre** [comment]
Of course, sorry for the late reply.

[latest.log](https://pastebin.com/2CY3Y2jP)

**Comment by maevius669** [comment]
I can confirm this happens on 1.21.
Exactly the same on 1.20.1 as well, with mod version 1.2.0, just tested.

**Comment by matthewperiut** [comment]
I fixed this for 1.21, I'll go back and fix old versions sometime soon! Thanks for the report turns out it happens at certain resolutions but I made a more robust calculation for this! I just uploaded 1.3.1 to modrinth and curseforge! Thanks guys
